### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by le0-VV** [nedrysoft/pingnoo#112]
Last commit and release are both more than 2 years ago, the dev doesn't seem to be active either

**Comment by chmac** [comment]
Any recommendations of a similar app that is maintained?

**Comment by le0-VV** [comment]
No, but honestly this project still works fine, I don't see a major reason to actively maintain it. It's just I submitted a pull request to update the app icon on macOS to follow the design convention (see pull request #113), and I still haven’t heard from the dev

**Comment by chmac** [comment]
Okay, thanks. I'll install it and see how I get on. Thanks for the super fast response! :-)

Haha, well, it crashes immediately on startup for me. At least, the home-brew version. Oh well, I guess I'll stick to prettyping in a terminal window...

**Comment by le0-VV** [comment]
Hmmm, that's odd. Which macOS version are you on? Is this what you’ve encountered?
￼

**Comment by chmac** [comment]
I'm on Sonoma 14.3. Brand new mac, will upgrade to 14.5 soon. I'm not sure what you mean "Is this what you've encountered?" Were you going to add a link or a screenshot or something?

When I start the app, I immediately get the "Pingnoo quit unexpectedly" error from macOS.

**Comment by le0-VV** [comment]
try go to /Applications, find pingnoo, ctrl+click the app and choose open, see if that works

**Comment by chmac** [comment]
It's not that kind of error. It looks like this:

<img width="372" alt="image" src="https://github.com/nedrysoft/pingnoo/assets/690997/c5d79c97-926a-4fba-874b-22e8db0cbcb5">

Looking at the report it talks about missing libraries:

```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
Referenced from: <4C260EAF-3092-3BFB-A949-ECEE6A713159> /Applications/Pingnoo.app/Contents/MacOS/Pingnoo
Reason: tried: '/Applications/Pingnoo.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/adriancarpenter/Downloads/buildAgentFull/work/47d95f567ff3ef24/cmake/../bin/arm64/Release/Pingnoo.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/adriancarpenter/Downloads/buildAgentFull/work/47d95f567ff3ef24/cmake/../bin/arm64/Release/Pingnoo.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets' (no such file), '/Users/adriancarpenter/Downloads/buildAgentFull/work/47d95f567ff3ef24/cmake/../bin/arm64/Release/Pingnoo.app/Contents/PlugIns/QtWidgets.framework/Versions/5/QtWidgets' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/adriancarpenter/Dow
(terminated at launch; ignore backtrace)
```

**Comment by le0-VV** [comment]
Tried the homebrew version, also crashed immediately, uninstall the brew version via brew uninstall pingnoo and try the version found on GitHub release tab, if the latest version doesn't work then try older versions

As for alternatives, the only one I can remember is PingPlotter, its **not** open source and it has some functions **paywalled**

**Comment by le0-VV** [comment]
https://github.com/nedrysoft/pingnoo/releases/tag/2021.06.22-develop
Verified to work

**Comment by chmac** [comment]
Ah, you're right, apple silicon support was only added in that release which is not on brew. I wonder if I can submit a PR to switch the brew release to that one. I guess it doesn't make sense for brew to be shipping a release that doesn't work.

That version works like a charm, thanks.

**Comment by le0-VV** [comment]
Dev just approved my PR so I guess it's not that dead, closing this issue
