### ISSUE TITLE
Main window is not focused after splash screen

### ISSUE THREAD

**Issue by Paulls20** [nedrysoft/pingnoo#12]
Main window is not focused after splash screen. Main window is always behind other application windows at start up.
Need to click on the notify popup in order to regain focus of the main window.

**Comment by fizzyade** [comment]
Yeah, I’ve noticed this in Linux (more specifically Fedora, I can't remember it doing it on Ubuntu.

I will fix this later.

Thanks for the report, I hadn't really considered that it was further reaching.
