### ISSUE TITLE
Multiple issue with Settings dialog.

### ISSUE THREAD

**Issue by Paulls20** [nedrysoft/pingnoo#14]
Multiple issue with Settings dialog.
1. Many Settings dialog can be opened at the same time.
2. Settings dialog is not closed even after the application is closed.
3. Sometimes the application crashes when Settings dialog is closed.
4. Typo **value)** in a button in Settings dialog.

**Comment by fizzyade** [comment]
Yeah, this is what I'm currently working on.  

1. The multiple settings dialog is a mistake, although the functionality differs on macOS against other OS's, under macOS the normal behaviour is that the window is not modal, under Linux and Windows it should be modal.
2. Related to 1, I'll fix.
3. Are you able to share instructions for repeating or any debug info?
4. I'll fix.

**Comment by Paulls20** [comment]
Steps to reproduce the crash:
fish: Job 2, “/home/paul/Workspace/pingnoo/bi…” terminated by signal SIGSEGV (Address boundary error)
![SettingsCrashed](https://user-images.githubusercontent.com/5001222/108241687-6328bf00-714c-11eb-8427-4cc4ff19daf1.gif)

**Comment by fizzyade** [comment]
Thanks, I will take a look.  I have fixed 1 & 2.  I cannot see the typo (sorry), where exactly is it?

Ok found it, it's on Windows/Linux.

**Comment by fizzyade** [comment]
What OS version are you getting the crash on, I can't repeat it here.

Also loving your terminal prompt!

(Thanks for the video, that's a super helpful way of providing feedback).

**Comment by fizzyade** [comment]
Fixes for 1,2 & 4 have been pushed.

**Comment by Paulls20** [comment]
It's not exactly a typo, but an extra closing bracket.
![image](https://user-images.githubusercontent.com/5001222/108263372-76488880-7166-11eb-95a4-02448a3336df.png)

**Comment by Paulls20** [comment]
> What OS version are you getting the crash on, I can't repeat it here.
> 
> Also loving your terminal prompt!
> 
> (Thanks for the video, that's a super helpful way of providing feedback).

I'm using ubuntu 20.04

**Comment by fizzyade** [comment]
Ok, I can repeat under 20.04!

**Comment by fizzyade** [comment]
item 3 (crash on close) is now fixed.

**Comment by fizzyade** [comment]
Just a small note, I still have to finish up some of the settings dialog, the hostmaskers section is mostly working, but the other pages need hooking up to persistent settings, I will fix this in the next couple of days.
