### ISSUE TITLE
Application does not launch on Windows 10. Gives me no message.

### ISSUE THREAD

**Issue by Ste-Mich** [nedrysoft/pingnoo#17]
I ran the windows installer. Installed the vc_redist as suggested.

Pingnoo.exe does not start. It only shows me the initial logo and then turns off.

(Just to make sure: Yes I did try restarting my computer. 😄)
Also I could not find a crash log, so I'am assuming one wasn't generated.

I read the docs. Based on those I shouldn't be missing any software.
(I do not have Qt installed.)

**Comment by fizzyade** [comment]
I have just tried a later installer I built last night for testing on a completely clean Windows 10 installation and it worked fine, I can't reproduce the fault you are describing.  One thing is that by default Windows 10 firewall will block the network access for the app, so either disable it or whitelist pingnoo.

Can you please try this installer to see if works let me know the outcome!

https://we.tl/t-b9PpZ9iLr4

**Comment by Ste-Mich** [comment]
That's weird. I tried installing in the default directory, whitelisting and even using the repair function.

Still the same. It just launches, but does not let me get past the logo.

Since this only happens on my computer, but not your clean install, could this be a problem with visual c++?

**Comment by fizzyade** [comment]
I don’t know why this would happen, one thing you can try is to go to the folder where it’s installed, you will see a folder named “Components”, inside that temporarily move out all the dll’s apart from Core.dll.  Do you have antivirus installed?

Try launching and see if it opens, if it does, then try moving plugins back into the folder one by one.

You should use the following order (and opening after each file has been copied):

HostIPGeoIPProvider.dll
IPAPIGeoIPProvider.dll
ICMPPingEngine.dll
RouteEngine.dll
RouteAnalyser.dll
RegExHostMasker.dll
PublicIPHostMasker.dll

**Comment by Ste-Mich** [comment]
I added each file one by one. The application did not launch when I added IPAPIGeoIPProvider.dll and HostIPGeoIPProvider.dll. Without those it seems to work all fine. 

I'am thinking this could be a problem with some geolocation IP stuff. I like to turn those things off in Windows. Could that be the problem?

**Comment by fizzyade** [comment]
@Ste-Mich cool, ok, we're getting somewhere at least!  Keep those files out of your installation for the moment, I will take a look to see if I have missed anything obvious that could be causing this, it's probably a nullptr not being caught by an assert or an actual runtime check.

It's minor in terms of functionality, so running without those for the moment isn't a huge issue.

I'll take a look tonight when I have finished work.

**Comment by fizzyade** [comment]
Edit: not going mad, it does, was looking in the wrong file.
Edit: going mad, it deosn't use SQL.

Ok, I know what the issue is, the QtSql library isn't being deployed along with the sqlite plugin.

**Comment by fizzyade** [comment]
This should be fixed now.  I will build binaries and add a link here for testing.

**Comment by fizzyade** [comment]
Can you uninstall and install this version:

https://we.tl/t-pq3VLjTEPr

As a bonus it should include the shortcut settings in the installer as well.

**Comment by Ste-Mich** [comment]
Amazing, thank you. It's working now.

**Comment by KestrelAdrian** [comment]
No worries, we got there in the end!  I will be pushing some new binaries shortly, I made some UI tweaks in the early hours of the morning, will be interested on feedback.
