### ISSUE TITLE
request/suggestion: Add a button for desktop shortcut creation during installation.

### ISSUE THREAD

**Issue by Ste-Mich** [nedrysoft/pingnoo#18]
I'am sure this will be added in time, as there are more important things right now.

I just wanted to open an issue so it is written in here.

**Comment by fizzyade** [comment]
It should create a desktop icon?  Or are you asking for that to be optional?

**Comment by Ste-Mich** [comment]
The latter. I like to keep my desktop clean, with minimal amount of things on it. (Usually zero 😄)

I think it is better whenever an installation ask you about it. Though again, I don't know how hard it is to implement and I'am sure there are more important things this early in development.

**Comment by fizzyade** [comment]
Fixed.  Thanks for the feedback.
