### ISSUE TITLE
Crashing when adding second host

### ISSUE THREAD

**Issue by jabertwo** [nedrysoft/pingnoo#32]
In the latest Version on Windows 10 20H2 when adding a second host the program crashes.

**Comment by fizzyade** [comment]
Can you provide me with repeatable steps to reproduce the problem?  

I tried under macOS at it worked correctly, I cant check windows until later.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/55795671/111156570-ce1fb700-858d-11eb-934e-b2c3fec6b63c.png">

**Comment by jabertwo** [comment]
1. Start tracing to first host
2. Click on File > New Target and enter information for second host
3. Click OK and Pingnoo will crash

I found that when I use the target field I am able to add the second host.

**Comment by fizzyade** [comment]
It must be windows specific.  I can't reproduce the crash here on macOS.  I will take a look later and get back to you.

Can I double-check that a Ping Engine is selected on the New Target dialog before you hit ok?

**Comment by jabertwo** [comment]
Yes, I selected ICMP Socket as the ping engine. I will try on another PC this evening.

**Comment by fizzyade** [comment]
@jabertwo I tried this last night, both on the latest development and also on the code from the last release, I was unable to get the application to crash.

My steps were:

1.) File/New Target, pressed OK without changing anything.
2.) File/New Target, changed host to 8.8.8.8 and pressed OK.

The application didn't crash for me.

**Comment by fizzyade** [comment]
@jabertwo did you manage to try this again?

**Comment by jabertwo** [comment]
Yes, I did try it on another machine where I didn't have the issue, so it seems like an issue with my specific pc only

**Comment by fizzyade** [comment]
> Yes, I did try it on another machine where I didn't have the issue, so it seems like an issue with my specific pc only

Very strange.  I'll add in minidump code to the Windows build which will generate a crash dump should the program crash, you will be able to send that to me and I can see what happened, it's going to be hard to figure out exactly what happened without this.

If you're willing to help (we all have lives outside of computers!) then I'll let you know when it's available to try.

**Comment by jabertwo** [comment]
I just tested with the latest version and the bug seems to be gone now. Probably just one of the many issues my windows installation has.

**Comment by fizzyade** [comment]
I'm going to close this, I suspect I fixed it in the last release.  

If the problem persists, feel free to re-open the issue.
