### ISSUE TITLE
ThemeSupport

### ISSUE THREAD

**Issue by fizzyade** [nedrysoft/pingnoo#47]
The ThemeSupport code is duplicated in a few places, for the sake of sanity, it needs to move to it's own library which other libraries & components can link to.

Additionally, add dark mode support for operating systems other than macOS.  Detecting it on other OS may be difficult (looking at you linux), so it may be "hacky" to detect on Linux, check the contrast between the text colour and window color to figure out if we should *probably* be in dark mode.

Add a setting for dark mode ("Detect System", "Dark", "Light")

**Comment by sxiii** [comment]
Good points! I'd be happy to test the dark theme as soon as possible :)

**Comment by fizzyade** [comment]
the initial issue with the code duplication has been solved by creating a shared library additionally it includes support for detecting dark mode on Linux (under GTK) so should look correct on system dark mode.

The additional "force" of light/dark mode is slightly more complicated, I am working on this in the background on another branch, but it's not a major priority.

I'm going to close this for the moment as the bug is fixed.
