### ISSUE TITLE
Mac add capability to scan version information

### ISSUE THREAD

**Issue by big610** [nedrysoft/pingnoo#50]
Add Mac capability to scan version number.  
The Mac version does not contain any version information internally. All Mac Apps are supposed yo have version information, therefore the ability to scan for an update is non readable to scan.

**Comment by fizzyade** [comment]
I'll add it to the plist, although it's not distributed via the App Store and neither does it have the ability to check for updates (hello sparkle!) so it's of limited use, but I take the point it should be there!

Thanks for the report, I will push a fix shortly.

**Comment by fizzyade** [comment]
fixed in #51

**Comment by big610** [comment]
Thank you, this will be useful for any 3rd party software, will then be read, scan the version, alert to an update.

**Comment by fizzyade** [comment]
> Thank you, this will be useful for any 3rd party software, will then be read, scan the version, alert to an update.

No problem.  Thanks for reporting, happy to accept bug reports, ideas, fixes, whatever!
