### ISSUE TITLE
Needs building instructions

### ISSUE THREAD

**Issue by AaronDMarasco** [nedrysoft/pingnoo#6]
It took me a while to get it build on a Fedora system, and even then it didn't run. The instructions say "just use git" and you only need qt and cmake.

I needed to clone submodules:

- `git submodule update --init --recursive`

Needed to install some prereqs:

- python-sphinx RPM
- python3-sphinx_rtd_theme RPM
- qt5-devel RPM
- sudo pip install sphinx-autobuild  # No RPM

Once there I was able to get the documentation up and running, but like I noted, it doesn't have actual instructions.

"Standard" install procedures worked once I figured out you were using git submodules (along with some changes):

- `mkdir build`
- `cd build`
- `cmake ..`
- ` make -j`

I started playing around with `deploy.py` but just ran into too many problems. I'll do a PR with the changes I needed noted above.

**Comment by fizzyade** [comment]
> It took me a while to get it build on a Fedora system, and even then it didn't run. The instructions say "just use git" and you only need qt and cmake.
> 
> I needed to clone submodules:
> 
> * `git submodule update --init --recursive`
> 
> Needed to install some prereqs:
> 
> * python-sphinx RPM
> * python3-sphinx_rtd_theme RPM
> * qt5-devel RPM
> * sudo pip install sphinx-autobuild  # No RPM
> 
> Once there I was able to get the documentation up and running, but like I noted, it doesn't have actual instructions.
> 
> "Standard" install procedures worked once I figured out you were using git submodules (along with some changes):
> 
> * `mkdir build`
> * `cd build`
> * `cmake ..`
> * ` make -j`
> 
> I started playing around with `deploy.py` but just ran into too many problems. I'll do a PR with the changes I needed noted above.

Hi, thanks for the feedback.  If you want to modify the README.md I will happily accept a PR (if you want credit) if not I will modify the README,md file myself to show the build process.

One slight caveat is that I've only tested fedora in the past few days when I decided that supplying an RPM for fedora would be a good idea, 

What issues did you have specifically with the deployment script?  I've been using it (and have made a load of changes over the weekend) without any issues, you just have to supply the correct parameters for the platform.  The CMakeLists.txt file in the root has the install targets in and shows the deploy.py parameters that are used on each platform - it's part of my CI system.

I guess it could be missing python modules, although it should download everything that it needs if it's not already there.

I appreciate you taking the time to raise the issues, I'm sure anybody who develops software is painfully aware that the developer often says "well, it works fine one mine!", so reports like yours are SUPER helpful in making the build/deployment process as painless as possible.

Oh I just saw you said you would create a PR, thank you! :D

**Comment by AaronDMarasco** [comment]
All I get is a splash screen then it hangs, so I'm not sure I have everything needed to make a useful executable. That's why I just provided my notes and didn't continue with the RPM stuff.

**Comment by fizzyade** [comment]
> All I get is a splash screen then it hangs, so I'm not sure I have everything needed to make a useful executable. That's why I just provided my notes and didn't continue with the RPM stuff.

Humn.  I wonder what's going on there, do you don't get the main window?  If you're not getting the main window, then it probably hasn't loaded the plugins.  How are you launching it?  Try from a terminal in binary folder, ./Pingnoo it should look in that folder for a "Components" folder which contains the plugins.

I can install fc32 myself and have a go later.

**Comment by AaronDMarasco** [comment]
Seems to be getting `EAGAIN` trying to read `/tmp/.X11-unix/X0`.

I finally saw your chat on Reddit if you have time.

**Comment by fizzyade** [comment]
> Seems to be getting `EAGAIN` trying to read `/tmp/.X11-unix/X0`.
> 
> I finally saw your chat on Reddit if you have time.

I'm working at the moment, but I will be finished in an hour so will be able to look.  /tmp.X11-unix sounds like it's something like the qt platform plugin.  That's not a folder (at least that I'm aware of) that I use.

You can launch the application with switches to select the framebuffer.

https://doc.qt.io/qt-5/linux-requirements.html

**Comment by fizzyade** [comment]
Also needs dbus-devel, so for the moment:

yum install dbus-devel

**Comment by fizzyade** [comment]
Ok, I installed fc32, cloned the repo and as above installed dbus-devel.

There's a mistake in the AppNap library which includes <QRecursiveMutex> which is only used by the mac port, so I'll add preprocessor to stop the error.

However, I made the minor change to the code and it compiled fine, I changed to the bin/x86_64/Release folder and executed ./Pingnoo and it worked fine.

**Comment by AaronDMarasco** [comment]
Weird; I don't boot into Fedora much, sorry. I'll try to look again later. I _think_ I had weird clipboard errors with the default Wayland so I was using a different XWindows interface. Not sure off-hand.

**Comment by fizzyade** [comment]
> Weird; I don't boot into Fedora much, sorry. I'll try to look again later. I _think_ I had weird clipboard errors with the default Wayland so I was using a different XWindows interface. Not sure off-hand.

I was running under X-org as Wayland is too slow over VNC, but I logged out and back in using Wayland and it worked the same.

It was a completely clean install of Fedora 32 and all I did was install dbus-devel.  If you get the chance to look, it would be nice to figure out why it didn't run on yours.

<img width="1041" alt="CleanShot 2021-02-15 at 21 26 47@2x" src="https://user-images.githubusercontent.com/55795671/107994465-934d5200-6fd4-11eb-9bb6-00cbab8be6fc.png">

**Comment by AaronDMarasco** [comment]
For posterity, this issue remains open, but my building issues went away with #9.

The `EAGAIN` was a red herring - https://unix.stackexchange.com/questions/275395/ddd-fails-to-connect-to-x-window-is-it-a-bug-or-a-local-misconfiguration

**Comment by fizzyade** [comment]
I'm going to close this one as build info has been added, feel free to re-open if you feel it needs more or I missed something.
